name: ZzzzzTuruWeb
id: 'ari:cloud:compass:b6128f24-d0f1-4fe8-8301-a7e9825a84fb:component/5c7ecbe0-5a25-46c2-abc3-e714305e9258/4334006d-03f6-496b-a050-2ad11a724344'
description: null
configVersion: 1
typeId: SERVICE
ownerId: null
fields:
  tier: 4
links:
  - name: null
    type: REPOSITORY
    url: 'https://github.com/GitZymzz/ZzzzzTuruWeb'
relationships: {}
labels:
  - 'language:css'
  - 'source:github'
customFields: null

# Learn more about formatting compass.yml:
# https://go.atlassian.com/compass-yml-format
